### ISSUE TITLE
FSLogix script should use group names for NTFS ACLs

### ISSUE THREAD

**Issue by SvenAelterman** [hooverken/ARMPowershell#5]
Currently, the FSLogix script configured NTFS ACLS for the generic "Users" principal. It's better to explicitly grant permissions only to the two groups that have permissions on the file share.

**Comment by hooverken** [comment]
The groups provided are used in IAM role assignments on the file share -- Storage File Data SMB Share Contributor / Elevated Contributor -- so it's not necessary to use the groups at the NTFS level (since the IAM roles are evaluated first).  The script currently uses well-known groups to keep things simple.  I'm going to close this since I think the current design is OK but happy to discuss if I'm missing something.

![image](https://user-images.githubusercontent.com/70644066/193278118-07ad79e1-2a8b-46bd-b8fe-c14ea2ec41db.png)
